# Generated by Django 2.2 on 2019-04-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beer_app.Review'),
            preserve_default=False,
        ),
    ]
